sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t denisaguilar/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true denisaguilar/docker-react npm run test
